# Generated by Django 4.1.4 on 2022-12-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='year',
            new_name='ent_year',
        ),
    ]
